<script setup lang="ts">
import { Lock, User } from '@element-plus/icons-vue'
import { ElMessage } from 'element-plus'
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { login } from '~/composables/auth'

/**
 * Login page component
 * Provides a form for users to authenticate with username and password
 *
 * For demonstration purposes, this component generates a mock JWT token.
 * In production, you should:
 * 1. Send credentials to your backend API
 * 2. Receive a real JWT token from the backend
 * 3. Store the token using the login() function
 */

const router = useRouter()

// Form data
const loginForm = ref({
  username: '',
  password: '',
})

// Loading state
const loading = ref(false)

/**
 * Generate a mock JWT token for demonstration
 * In production, this token should come from your backend API
 *
 * Backend Integration Instructions:
 * --------------------------------
 * Replace this function with an API call to your backend:
 *
 * async function handleLogin() {
 *   loading.value = true
 *   try {
 *     const response = await fetch('https://your-api.com/auth/login', {
 *       method: 'POST',
 *       headers: { 'Content-Type': 'application/json' },
 *       body: JSON.stringify({
 *         username: loginForm.value.username,
 *         password: loginForm.value.password,
 *       }),
 *     })
 *     const data = await response.json()
 *     if (data.token) {
 *       login(data.token)
 *       // ... rest of the code
 *     }
 *   } catch (error) {
 *     ElMessage.error('Login failed. Please try again.')
 *   } finally {
 *     loading.value = false
 *   }
 * }
 */
function generateMockToken(username: string): string {
  // Mock JWT header and payload
  const header = {
    alg: 'HS256',
    typ: 'JWT',
  }

  const payload = {
    sub: username,
    email: `${username}@example.com`,
    role: 'user',
    iat: Math.floor(Date.now() / 1000),
    exp: Math.floor(Date.now() / 1000) + (60 * 60 * 24), // 24 hours
  }

  // Base64url encode (simplified for demo - not cryptographically secure)
  const base64Header = btoa(JSON.stringify(header))
    .replace(/\+/g, '-')
    .replace(/\//g, '_')
    .replace(/=/g, '')
  const base64Payload = btoa(JSON.stringify(payload))
    .replace(/\+/g, '-')
    .replace(/\//g, '_')
    .replace(/=/g, '')

  // Mock signature (in production, this is generated by your backend using a secret key)
  const signature = 'mock_signature_replace_with_real_backend_token'

  return `${base64Header}.${base64Payload}.${signature}`
}

/**
 * Handle login form submission
 */
async function handleLogin() {
  // Basic validation
  if (!loginForm.value.username || !loginForm.value.password) {
    ElMessage.warning('Please enter both username and password')
    return
  }

  loading.value = true

  // Simulate API call delay
  await new Promise(resolve => setTimeout(resolve, 500))

  // In this demo, accept any credentials
  // In production, your backend should validate credentials
  const mockToken = generateMockToken(loginForm.value.username)

  // Store the token
  const success = login(mockToken)

  if (success) {
    ElMessage.success('Login successful!')

    // Redirect to the original destination or home page
    const redirect = router.currentRoute.value.query.redirect as string
    await router.push(redirect || '/')
  }
  else {
    ElMessage.error('Invalid token. Please try again.')
  }

  loading.value = false
}
</script>

<template>
  <div class="login-container">
    <el-card class="login-card" shadow="hover">
      <template #header>
        <div class="card-header">
          <h2>Login</h2>
          <p class="subtitle">
            Sign in to access protected pages
          </p>
        </div>
      </template>

      <el-form
        :model="loginForm"
        label-position="top"
        @submit.prevent="handleLogin"
      >
        <el-form-item label="Username">
          <el-input
            v-model="loginForm.username"
            :prefix-icon="User"
            placeholder="Enter any username"
            size="large"
          />
        </el-form-item>

        <el-form-item label="Password">
          <el-input
            v-model="loginForm.password"
            :prefix-icon="Lock"
            type="password"
            placeholder="Enter any password"
            size="large"
            @keyup.enter="handleLogin"
          />
        </el-form-item>

        <el-form-item>
          <el-button
            type="primary"
            :loading="loading"
            size="large"
            style="width: 100%"
            @click="handleLogin"
          >
            Login
          </el-button>
        </el-form-item>
      </el-form>

      <el-divider />

      <div class="demo-info">
        <el-alert
          title="Demo Mode"
          type="info"
          :closable="false"
          show-icon
        >
          <p>This is a demonstration of JWT authentication.</p>
          <p>Enter any username and password to login.</p>
          <p><strong>In production:</strong> Replace the mock token generation with a real API call to your backend.</p>
        </el-alert>
      </div>
    </el-card>
  </div>
</template>

<style scoped>
.login-container {
  display: flex;
  justify-content: center;
  align-items: center;
  min-height: 100%;
  padding: 20px;
}

.login-card {
  width: 100%;
  max-width: 450px;
}

.card-header {
  text-align: center;
}

.card-header h2 {
  margin: 0 0 8px 0;
  font-size: 24px;
  color: var(--ep-text-color-primary);
}

.subtitle {
  margin: 0;
  font-size: 14px;
  color: var(--ep-text-color-secondary);
}

.demo-info {
  margin-top: 16px;
}

.demo-info p {
  margin: 4px 0;
  font-size: 13px;
}
</style>
